---
title: Order XY - Mobile ordering solutions
author: OrderXY.com
email: support@orderxy.com
description: OrderXY is a mobile ordering solution that gives the power and control
  over the products and customers back to the venue owners.
baseurl: "/ubuild-jekyll"
url: order.xy.com
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
